fix constructor for debug compilation
wouterboomsma/eigency pull request #67
Opened 2023-11-08 14:57 UTC by fbordeu

Cython in debug configuration generetate the following code (compiled with -UNDEBUG):

    ....
    eigency::FlattenedMap<Eigen::Matrix,Muscat::CMuscatIndex,Eigen::Dynamic,1>  __pyx_t_2;
    ....
    try {
       __pyx_t_2 = eigency::FlattenedMap<Eigen::Matrix,Muscat::CMuscatIndex,Eigen::Dynamic,1> (((PyArrayObject *)__pyx_v_ids));
    } catch(...) {
    ....

Need a correction of the default constructor to adapt to the correct size ( (Eigen::Dynamic,1)  in this case)  .

Felipe

2023-11-22 15:31 UTC, fbordeu commented
@BTOdell any idea if this branch can be merge??

2023-11-22 19:27 UTC, BTOdell requested changes
It might just be the formatting on my phone, but can you fix the formatting around the ternary statement to have space around the `:` character and not before the `)` character at the end of the line?

Overall the change seems fine. Does this issue only happen during debug compilation? It seems like a core implementation detail.

2023-11-24 08:50 UTC, fbordeu commented
> It might just be the formatting on my phone, but can you fix the formatting around the ternary statement to have space around the `:` character and also no space before the `)` character at the end of the line?

Just pushed the changes, tell me if I need to change anything else.

> 
> Overall the change seems fine. Does this issue only happen during debug compilation? It seems like a core implementation detail.

I did some investigation, and actually the code generated (by cython) in debug and in release is the same. I think the problem is Eigen not doing size checking in release.

2023-11-24 08:56 UTC, BTOdell approved these changes

2023-11-24 09:00 UTC, merged

2023-11-24 09:01 UTC, BTOdell commented
Thanks for the contribution. I'll work on creating a new release asap.

2023-11-24 09:19 UTC, BTOdell commented
Done: https://pypi.org/project/eigency/3.4.0.2/

2023-11-24 13:42 UTC, fbordeu commented
cool, thanks